BEGIN TRANSACTION;
DROP TABLE IF EXISTS "USERS";
CREATE TABLE IF NOT EXISTS "USERS" (
	"id"	INTEGER,
	"name"	TEXT,
	"surname"	TEXT,
	"username"	TEXT,
	"type"	TEXT,
	"password"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "SKUS";
CREATE TABLE IF NOT EXISTS "SKUS" (
	"id"	INTEGER NOT NULL,
	"description"	VARCHAR,
	"weight"	INTEGER,
	"volume"	INTEGER,
	"notes"	VARCHAR,
	"position"	BIGINT,
	"availableQuantity"	INTEGER,
	"price"	DECIMAL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "RESTOCK_ORDERS";
CREATE TABLE IF NOT EXISTS "RESTOCK_ORDERS" (
	"id"	INTEGER NOT NULL,
	"issueDate"	TEXT,
	"state"	TEXT,
	"supplierId"	INTEGER,
	"transportNote"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "TEST_RESULTS";
CREATE TABLE IF NOT EXISTS "TEST_RESULTS" (
	"id"	INTEGER NOT NULL,
	"idTestDescriptor"	NUMERIC,
	"date"	TEXT,
	"result"	TEXT,
	"rfid"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "TEST_DESCRIPTORS";
CREATE TABLE IF NOT EXISTS "TEST_DESCRIPTORS" (
	"id"	INTEGER,
	"name"	TEXT,
	"procedureDescription"	TEXT,
	"idSKU"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "SKUItems";
CREATE TABLE IF NOT EXISTS "SKUItems" (
	"RFID"	VARCHAR(32) NOT NULL,
	"SKUId"	INTEGER,
	"Available"	BOOLEAN,
	"DateOfStock"	DATE,
	"RestockOrder"	INTEGER,
	"ReturnOrderId"	INTEGER,
	"InternalOrderId"	INTEGER,
	PRIMARY KEY("RFID")
);
DROP TABLE IF EXISTS "RO_PRODUCTS";
CREATE TABLE IF NOT EXISTS "RO_PRODUCTS" (
	"RestockOrderId"	INTEGER NOT NULL,
	"SKUId"	INTEGER NOT NULL,
	"quantity"	INTEGER,
	PRIMARY KEY("RestockOrderId","SKUId")
);
DROP TABLE IF EXISTS "RETURN_ORDERS";
CREATE TABLE IF NOT EXISTS "RETURN_ORDERS" (
	"returnOrderId"	INTEGER NOT NULL,
	"restockOrderId"	INTEGER,
	"returnDate"	TEXT,
	PRIMARY KEY("returnOrderId" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "POSITIONS";
CREATE TABLE IF NOT EXISTS "POSITIONS" (
	"positionID"	BIGINT NOT NULL,
	"aisleID"	INTEGER,
	"row"	INTEGER,
	"col"	INTEGER,
	"maxWeight"	INTEGER,
	"maxVolume"	INTEGER,
	"occupiedWeight"	INTEGER,
	"occupiedVolume"	INTEGER,
	PRIMARY KEY("positionID")
);
DROP TABLE IF EXISTS "ITEMS";
CREATE TABLE IF NOT EXISTS "ITEMS" (
	"id"	INTEGER NOT NULL,
	"description"	TEXT,
	"price"	FLOAT,
	"SKUId"	INTEGER,
	"supplierId"	INTEGER,
	PRIMARY KEY("id", "supplierId")
);
DROP TABLE IF EXISTS "IO_PRODUCTS";
CREATE TABLE IF NOT EXISTS "IO_PRODUCTS" (
	"SKUId"	INTEGER NOT NULL,
	"InternalOrderId"	INTEGER NOT NULL,
	"description"	TEXT,
	"price"	FLOAT,
	"quantity"	INTEGER,
	PRIMARY KEY("SKUId","InternalOrderId")
);
DROP TABLE IF EXISTS "INTERNAL_ORDERS";
CREATE TABLE IF NOT EXISTS "INTERNAL_ORDERS" (
	"id"	INTEGER,
	"issueDate"	DATE,
	"state"	TEXT,
	"customerId"	INTEGER,
	PRIMARY KEY("id")
);
COMMIT;
